# Generated by Django 5.1.5 on 2025-01-29 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interpreter",
            name="account_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="interpreter",
            name="routing_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
