# Generated by Django 5.1.5 on 2025-02-07 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_create_assignment_notification"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="assignmentnotification",
            new_name="app_assignm_interpr_0de326_idx",
            old_name="app_assignm_interpr_idx",
        ),
        migrations.RenameIndex(
            model_name="assignmentnotification",
            new_name="app_assignm_created_6849c4_idx",
            old_name="app_assignm_created_idx",
        ),
    ]
