# Generated by Django 5.1.5 on 2025-02-08 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "app",
            "0005_rename_app_assignm_interpr_idx_app_assignm_interpr_0de326_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="client_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="assignment",
            name="client_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="assignment",
            name="client_phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="app.client",
            ),
        ),
    ]
