# Generated by Django 5.1.5 on 2025-02-09 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_assignment_client_email_assignment_client_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignment",
            name="interpreter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="app.interpreter",
            ),
        ),
    ]
