# Generated by Django 5.1.5 on 2025-02-14 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_payrolldocument_service"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payrolldocument",
            name="account_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="payrolldocument",
            name="bank_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="payrolldocument",
            name="company_address",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="payrolldocument",
            name="company_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name="payrolldocument",
            name="company_logo",
            field=models.ImageField(blank=True, upload_to="company_logos/"),
        ),
        migrations.AlterField(
            model_name="payrolldocument",
            name="company_phone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="payrolldocument",
            name="interpreter_address",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="payrolldocument",
            name="interpreter_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name="payrolldocument",
            name="interpreter_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="payrolldocument",
            name="interpreter_phone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="payrolldocument",
            name="routing_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="service",
            name="client",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="service",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="service",
            name="duration",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="rate",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="source_language",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="service",
            name="target_language",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
