# Generated by Django 5.1.5 on 2025-02-20 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_alter_payrolldocument_account_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="is_paid",
            field=models.BooleanField(
                blank=True,
                help_text="Indicates if the assignment has been paid",
                null=True,
            ),
        ),
    ]
