# Generated by Django 5.1.5 on 2025-02-20 18:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0012_assignment_is_paid"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="interpreterpayment",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Interpreter Payment",
                "verbose_name_plural": "Interpreter Payments",
            },
        ),
        migrations.AddField(
            model_name="interpreterpayment",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False
            ),
        ),
        migrations.AddField(
            model_name="interpreterpayment",
            name="updated_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="interpreterpayment",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("PROCESSING", "Processing"),
                    ("COMPLETED", "Completed"),
                    ("FAILED", "Failed"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="interpreterpayment",
            index=models.Index(
                fields=["status", "scheduled_date"],
                name="app_interpr_status_ec837e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="interpreterpayment",
            index=models.Index(
                fields=["interpreter", "status"], name="app_interpr_interpr_fe77ae_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="interpreterpayment",
            index=models.Index(
                fields=["created_at"], name="app_interpr_created_3b2b83_idx"
            ),
        ),
    ]
