# Generated by Django 5.1.5 on 2025-02-27 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0013_alter_interpreterpayment_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
