# Generated by Django 5.1.5 on 2025-02-27 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0014_client_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
