# Generated by Django 5.1.5 on 2025-02-27 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0015_client_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="Deduction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(blank=True, null=True)),
                ("description", models.CharField(max_length=255)),
                (
                    "deduction_type",
                    models.CharField(
                        choices=[
                            ("ADVANCE", "Payment advance"),
                            ("EQUIPMENT", "Provided equipment"),
                            ("CANCELLATION", "Cancellation penalty"),
                            ("LATE", "Late penalty"),
                            ("TAX", "Tax withholding"),
                            ("CONTRIBUTION", "Social contributions"),
                            ("ADMIN_FEE", "Administrative fees"),
                            ("ADJUSTMENT", "Invoice adjustment"),
                            ("OTHER", "Other deduction"),
                        ],
                        default="OTHER",
                        max_length=50,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "payroll",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deductions",
                        to="app.payrolldocument",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Reimbursement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(blank=True, null=True)),
                ("description", models.CharField(max_length=255)),
                (
                    "reimbursement_type",
                    models.CharField(
                        choices=[
                            ("TRANSPORT", "Transportation"),
                            ("PARKING", "Parking fees"),
                            ("TOLL", "Toll fees"),
                            ("MEAL", "Meals"),
                            ("ACCOMMODATION", "Accommodation"),
                            ("EQUIPMENT", "Interpretation equipment"),
                            ("TRAINING", "Professional training"),
                            ("COMMUNICATION", "Communication fees"),
                            ("PRINTING", "Document printing"),
                            ("OTHER", "Other reimbursable expense"),
                        ],
                        default="OTHER",
                        max_length=50,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "receipt",
                    models.FileField(blank=True, null=True, upload_to="receipts/"),
                ),
                (
                    "payroll",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reimbursements",
                        to="app.payrolldocument",
                    ),
                ),
            ],
        ),
    ]
