# Generated by Django 5.2 on 2025-05-03 03:23

import app.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0017_apikey_interpretercontractsignature"),
    ]

    operations = [
        migrations.AddField(
            model_name="interpretercontractsignature",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="interpretercontractsignature",
            name="expires_at",
            field=models.DateTimeField(default=app.models.get_expiration_time),
        ),
        migrations.AddField(
            model_name="interpretercontractsignature",
            name="interpreter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contracts",
                to="app.interpreter",
            ),
        ),
        migrations.AddField(
            model_name="interpretercontractsignature",
            name="otp_code",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name="interpretercontractsignature",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("SIGNED", "Signed"),
                    ("EXPIRED", "Expired"),
                    ("REJECTED", "Rejected"),
                    ("COMPLETED", "Completed"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="interpretercontractsignature",
            name="token",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="interpretercontractsignature",
            name="account_type",
            field=models.CharField(
                blank=True,
                choices=[("checking", "Checking"), ("savings", "Savings")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="interpretercontractsignature",
            name="bank_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="interpretercontractsignature",
            name="contract_document",
            field=models.FileField(
                blank=True, null=True, upload_to="interpreter_contracts/"
            ),
        ),
        migrations.AlterField(
            model_name="interpretercontractsignature",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="interpretercontractsignature",
            name="signature_hash",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="interpretercontractsignature",
            name="signature_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("image", "Uploaded image"),
                    ("typography", "Typography signature"),
                    ("manual", "Manual signature"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="interpretercontractsignature",
            name="signed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="SignedDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "original_document",
                    models.FileField(upload_to=app.models.pdf_upload_path),
                ),
                (
                    "signed_document",
                    models.FileField(
                        blank=True, null=True, upload_to=app.models.pdf_upload_path
                    ),
                ),
                (
                    "signature_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=app.models.signature_upload_path,
                    ),
                ),
                (
                    "signature_type",
                    models.CharField(
                        choices=[
                            ("handwritten", "Signature manuscrite"),
                            ("image", "Image de signature"),
                            ("typographic", "Signature typographique"),
                        ],
                        max_length=20,
                    ),
                ),
                ("signature_position", models.JSONField(default=dict)),
                ("signature_metadata", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
