# Generated by Django 5.2 on 2025-05-03 04:31
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_interpretercontractsignature_created_at_and_more'),  # Remplacez ceci par la dernière migration dans votre app
    ]

    operations = [
    ]