# Generated by Django 5.2 on 2025-05-03 04:31
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_interpretercontractsignature_created_at_and_more'),  # Remplacez ceci par la dernière migration dans votre app
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_quote_updates', models.BooleanField(default=True, help_text='Receive email notifications about quote status updates')),
                ('email_assignment_updates', models.BooleanField(default=True, help_text='Receive email notifications about assignment updates')),
                ('email_payment_updates', models.BooleanField(default=True, help_text='Receive email notifications about payment status')),
                ('sms_enabled', models.BooleanField(default=False, help_text='Enable SMS notifications')),
                ('quote_notifications', models.BooleanField(default=True, help_text='Receive in-app notifications about quotes')),
                ('assignment_notifications', models.BooleanField(default=True, help_text='Receive in-app notifications about assignments')),
                ('payment_notifications', models.BooleanField(default=True, help_text='Receive in-app notifications about payments')),
                ('system_notifications', models.BooleanField(default=True, help_text='Receive system notifications and updates')),
                ('notification_frequency', models.CharField(choices=[('immediate', 'Immediate'), ('daily', 'Daily Digest'), ('weekly', 'Weekly Digest')], default='immediate', help_text='How often to receive notifications', max_length=20)),
                ('preferred_language', models.ForeignKey(blank=True, help_text='Preferred language for notifications', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.language')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
            },
        ),
    ]