# Generated by Django 5.2 on 2025-05-04 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0019_notif"),
    ]

    operations = [
        migrations.AddField(
            model_name="interpretercontractsignature",
            name="signature_typography_font",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="interpretercontractsignature",
            name="signature_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("upload", "Uploaded image"),
                    ("type", "Typography signature"),
                    ("draw", "Manual signature"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
