# Generated by Django 5.2 on 2025-05-10 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0021_pgpkey_document_documentauditlog_documentmetadata_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="documentauditlog",
            name="document",
        ),
        migrations.RemoveField(
            model_name="documentauditlog",
            name="user",
        ),
        migrations.DeleteModel(
            name="DocumentMetadata",
        ),
        migrations.DeleteModel(
            name="DocumentAuditLog",
        ),
    ]
