# Generated by Django 5.2 on 2025-05-10 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0022_remove_documentauditlog_document_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="interpretercontractsignature",
            name="signature_converted_url",
            field=models.CharField(
                blank=True,
                help_text="URL S3 de la signature manuelle convertie en PNG",
                max_length=500,
                null=True,
            ),
        ),
    ]
