# Generated by Django 5.2 on 2025-05-11 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0023_interpretercontractsignature_signature_converted_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interpretercontractsignature",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("SIGNED", "Signed"),
                    ("EXPIRED", "Expired"),
                    ("LINK_ACCESSED", "Link_accessed"),
                    ("REJECTED", "Rejected"),
                    ("COMPLETED", "Completed"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
