# Generated by Django 5.2 on 2025-05-11 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0024_alter_interpretercontractsignature_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="interpretercontractsignature",
            name="account_holder_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
