# Generated by Django 5.1.3 on 2026-02-03 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_interpreter_contract_acceptance_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contract_acceptance_date',
            field=models.DateTimeField(blank=True, help_text="Date d'acceptation du contrat", null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_dashboard_enabled',
            field=models.BooleanField(default=False, help_text='Accès au tableau de bord activé'),
        ),
    ]
