# Generated by Django 5.1.3 on 2026-02-04 11:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_user_contract_acceptance_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invitation_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('status', models.CharField(choices=[('SENT', 'Email Sent'), ('OPENED', 'Email Opened'), ('REVIEWING', 'Reviewing Contract'), ('SIGNED', 'Accepted & Signed'), ('VOIDED', 'Voided by Admin'), ('EXPIRED', 'Invitation Expired')], default='SENT', max_length=20)),
                ('version', models.IntegerField(default=1)),
                ('token', models.CharField(db_index=True, max_length=100, unique=True)),
                ('accept_token', models.CharField(db_index=True, max_length=100, unique=True)),
                ('review_token', models.CharField(db_index=True, max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email_sent_at', models.DateTimeField(auto_now_add=True)),
                ('email_opened_at', models.DateTimeField(blank=True, null=True)),
                ('link_clicked_at', models.DateTimeField(blank=True, null=True)),
                ('link_clicked_type', models.CharField(blank=True, max_length=20, null=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('void_reason', models.TextField(blank=True, null=True)),
                ('pdf_s3_key', models.CharField(blank=True, max_length=500, null=True)),
                ('contract_signature', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitation', to='app.interpretercontractsignature')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_invitations', to=settings.AUTH_USER_MODEL)),
                ('interpreter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_invitations', to='app.interpreter')),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voided_invitations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'app_contract_invitation',
            },
        ),
        migrations.CreateModel(
            name='ContractTrackingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('EMAIL_SENT', 'Email Sent'), ('EMAIL_OPENED', 'Email Opened'), ('ACCEPT_LINK_CLICKED', 'Accept Link Clicked'), ('REVIEW_LINK_CLICKED', 'Review Link Clicked'), ('WIZARD_STARTED', 'Wizard Started'), ('WIZARD_COMPLETED', 'Wizard Completed'), ('CONTRACT_SIGNED', 'Contract Signed'), ('PDF_GENERATED', 'PDF Generated'), ('CONFIRMATION_EMAIL_SENT', 'Confirmation Email Sent'), ('VOIDED', 'Voided by Admin'), ('RESENT', 'Invitation Resent')], max_length=30)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(default=dict)),
                ('invitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_events', to='app.contractinvitation')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'app_contract_tracking_event',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='contractinvitation',
            index=models.Index(fields=['token'], name='app_contrac_token_b0eab7_idx'),
        ),
        migrations.AddIndex(
            model_name='contractinvitation',
            index=models.Index(fields=['accept_token'], name='app_contrac_accept__b837c9_idx'),
        ),
        migrations.AddIndex(
            model_name='contractinvitation',
            index=models.Index(fields=['review_token'], name='app_contrac_review__dfb109_idx'),
        ),
        migrations.AddIndex(
            model_name='contractinvitation',
            index=models.Index(fields=['status'], name='app_contrac_status_9060d0_idx'),
        ),
        migrations.AddIndex(
            model_name='contractinvitation',
            index=models.Index(fields=['invitation_number'], name='app_contrac_invitat_316219_idx'),
        ),
    ]
