# Generated by Django 5.1.3 on 2026-02-10 18:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_contractinvitation_contracttrackingevent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interpreter',
            name='blocked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interpreter',
            name='blocked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocked_interpreters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='interpreter',
            name='blocked_reason',
            field=models.TextField(blank=True, help_text='Raison du blocage', null=True),
        ),
        migrations.AddField(
            model_name='interpreter',
            name='is_manually_blocked',
            field=models.BooleanField(default=False, help_text='Bloqué manuellement par un administrateur'),
        ),
        migrations.AddField(
            model_name='interpretercontractsignature',
            name='signature_method',
            field=models.CharField(choices=[('WIZARD', 'Wizard Checkbox'), ('LEGACY', 'Legacy OTP/Draw'), ('UPLOAD', 'Manual Upload'), ('DIGITAL_CHECKBOX', 'Digital Checkbox (Wizard)')], default='LEGACY', help_text='Method used to sign the contract', max_length=20),
        ),
        migrations.CreateModel(
            name='ContractReminder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.IntegerField(choices=[(1, 'Level 1 - Initial Reminder (3 days)'), (2, 'Level 2 - Urgent Reminder (7 days)'), (3, 'Level 3 - Final Notice & Block (14 days)')])),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('interpreter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_reminders', to='app.interpreter')),
                ('invitation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reminders', to='app.contractinvitation')),
                ('sent_by', models.ForeignKey(blank=True, help_text='User who triggered the reminder (null if automated)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'app_contract_reminder',
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['interpreter', 'level'], name='app_contrac_interpr_bed905_idx'), models.Index(fields=['sent_at'], name='app_contrac_sent_at_5d3d54_idx')],
            },
        ),
    ]
