# Generated by Django 5.1.3 on 2026-03-10 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_interpreter_blocked_at_interpreter_blocked_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interpreter',
            name='assignment_types',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interpreter',
            name='cities_willing_to_cover',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interpreter',
            name='contract_invite_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interpreter',
            name='contract_invite_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='interpreter',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interpreter',
            name='preferred_assignment_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='interpreter',
            name='signature_ip',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='interpreter',
            name='years_of_experience',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='interpreter',
            name='profile_image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
