# Generated by Django 5.1.3 on 2026-03-11 01:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_interpreter_assignment_types_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invitation_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('current_phase', models.CharField(choices=[('INVITED', 'Invitation Sent'), ('EMAIL_OPENED', 'Email Opened'), ('WELCOME_VIEWED', 'Welcome Viewed'), ('ACCOUNT_CREATED', 'Account Created'), ('PROFILE_COMPLETED', 'Profile Completed'), ('CONTRACT_STARTED', 'Contract Started'), ('COMPLETED', 'Fully Completed'), ('VOIDED', 'Voided'), ('EXPIRED', 'Expired')], default='INVITED', max_length=20)),
                ('version', models.IntegerField(default=1)),
                ('token', models.CharField(db_index=True, max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('email_opened_at', models.DateTimeField(blank=True, null=True)),
                ('welcome_viewed_at', models.DateTimeField(blank=True, null=True)),
                ('account_created_at', models.DateTimeField(blank=True, null=True)),
                ('profile_completed_at', models.DateTimeField(blank=True, null=True)),
                ('contract_started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('void_reason', models.TextField(blank=True, null=True)),
                ('contract_invitation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarding', to='app.contractinvitation')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_onboarding_invitations', to=settings.AUTH_USER_MODEL)),
                ('interpreter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarding_invitations', to='app.interpreter')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarding_invitations', to=settings.AUTH_USER_MODEL)),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voided_onboarding_invitations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'app_onboarding_invitation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OnboardingTrackingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('EMAIL_SENT', 'Invitation Email Sent'), ('EMAIL_OPENED', 'Email Opened'), ('LINK_CLICKED', 'Onboarding Link Clicked'), ('WELCOME_COMPLETED', 'Welcome Phase Completed'), ('ACCOUNT_CREATED', 'Account Created'), ('PROFILE_SAVED', 'Profile Saved'), ('CONTRACT_STARTED', 'Contract Wizard Started'), ('CONTRACT_SIGNED', 'Contract Signed'), ('ONBOARDING_COMPLETED', 'Onboarding Fully Completed'), ('VOIDED', 'Voided by Admin'), ('RESENT', 'Invitation Resent')], max_length=30)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(default=dict)),
                ('invitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_events', to='app.onboardinginvitation')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'app_onboarding_tracking_event',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='onboardinginvitation',
            index=models.Index(fields=['token'], name='app_onboard_token_d8bbd0_idx'),
        ),
        migrations.AddIndex(
            model_name='onboardinginvitation',
            index=models.Index(fields=['email'], name='app_onboard_email_14e220_idx'),
        ),
        migrations.AddIndex(
            model_name='onboardinginvitation',
            index=models.Index(fields=['current_phase'], name='app_onboard_current_a19b5a_idx'),
        ),
    ]
