# Generated by Django 6.0.3 on 2026-03-18 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_campaign_lead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('QUOTE_REQUEST', 'Quote Request'), ('QUOTE_READY', 'Quote Ready'), ('ASSIGNMENT_OFFER', 'Assignment Offer'), ('ASSIGNMENT_REMINDER', 'Assignment Reminder'), ('PAYMENT_RECEIVED', 'Payment Received'), ('PAYMENT_REMINDER', 'Payment Reminder'), ('SYSTEM', 'System')], max_length=20),
        ),
    ]
