# Generated by Django 6.0.3 on 2026-03-20 17:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_alter_notification_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('success', models.BooleanField(default=False)),
                ('failure_reason', models.CharField(blank=True, default='', max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'app_login_attempt',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['email', '-timestamp'], name='app_login_a_email_d88cea_idx'), models.Index(fields=['ip_address', '-timestamp'], name='app_login_a_ip_addr_986d6e_idx')],
            },
        ),
        migrations.CreateModel(
            name='MFABackupCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code_hash', models.CharField(help_text='SHA-256 hash of the backup code', max_length=64)),
                ('used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mfa_backup_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'MFA Backup Code',
                'db_table': 'app_mfa_backup_code',
            },
        ),
        migrations.CreateModel(
            name='MFADevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('secret', models.CharField(help_text='Base32-encoded TOTP secret', max_length=64)),
                ('is_verified', models.BooleanField(default=False, help_text='True once the user has confirmed their first TOTP code')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mfa_device', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'MFA Device',
                'verbose_name_plural': 'MFA Devices',
                'db_table': 'app_mfa_device',
            },
        ),
        migrations.CreateModel(
            name='TrustedDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_fingerprint', models.CharField(help_text='SHA-256 hash of browser fingerprint data', max_length=64)),
                ('token_hash', models.CharField(help_text='SHA-256 hash of the trust token sent to the client', max_length=64, unique=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trusted_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trusted Device',
                'verbose_name_plural': 'Trusted Devices',
                'db_table': 'app_trusted_device',
            },
        ),
        migrations.CreateModel(
            name='WebAuthnCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('credential_id_b64', models.CharField(help_text='Base64-encoded FIDO2 credential ID', max_length=512, unique=True)),
                ('public_key_b64', models.TextField(help_text='Base64-encoded CBOR public key')),
                ('sign_count', models.PositiveIntegerField(default=0)),
                ('device_name', models.CharField(default='Unknown Device', max_length=100)),
                ('transports', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webauthn_credentials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'WebAuthn Credential',
                'verbose_name_plural': 'WebAuthn Credentials',
                'db_table': 'app_webauthn_credential',
            },
        ),
    ]
