# Generated by Django 6.0.3 on 2026-03-22 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_loginattempt_mfabackupcode_mfadevice_trusteddevice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='gcal_event_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='gcal_sync_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SYNCED', 'Synced'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped'), ('DELETED', 'Deleted')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='assignment',
            name='gcal_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
