# Generated by Django 6.0.3 on 2026-03-22 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_gcal_sync_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentQueueItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmail_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('email_subject', models.CharField(blank=True, max_length=500)),
                ('email_from', models.CharField(blank=True, max_length=254)),
                ('category', models.CharField(choices=[('INTERPRETATION', 'Interpretation Request'), ('QUOTE', 'Quote Request'), ('HIRING', 'Hiring / CV'), ('INVOICE', 'Invoice Received'), ('PAYSLIP', 'Payslip Received'), ('PAYMENT', 'Payment Confirmation'), ('CONFIRMATION', 'Confirmation'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('confidence', models.FloatField(default=0.0)),
                ('extracted_data', models.JSONField(default=dict)),
                ('action_type', models.CharField(choices=[('CREATE_ASSIGNMENT', 'Create Assignment'), ('CREATE_QUOTE_REQUEST', 'Create Quote Request'), ('SEND_ONBOARDING', 'Send Onboarding Invitation'), ('RECORD_INVOICE', 'Record Payable Invoice'), ('RECORD_PAYSLIP', 'Record Payslip'), ('MARK_INVOICE_PAID', 'Mark Invoice Paid'), ('SEND_REPLY', 'Send Email Reply'), ('CREATE_CLIENT', 'Create Client'), ('MANUAL_REVIEW', 'Manual Review Required')], default='MANUAL_REVIEW', max_length=30)),
                ('action_payload', models.JSONField(default=dict)),
                ('ai_reasoning', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('EXECUTING', 'Executing'), ('DONE', 'Done'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=15)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('result', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('linked_assignment_id', models.BigIntegerField(blank=True, null=True)),
                ('linked_client_id', models.BigIntegerField(blank=True, null=True)),
                ('linked_onboarding_id', models.CharField(blank=True, max_length=36)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_agent_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Agent Queue Item',
                'verbose_name_plural': 'Agent Queue Items',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('entity_type', models.CharField(blank=True, max_length=50)),
                ('entity_id', models.CharField(blank=True, max_length=50)),
                ('success', models.BooleanField(default=True)),
                ('details', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('queue_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='app.agentqueueitem')),
            ],
            options={
                'verbose_name': 'Agent Audit Log',
                'verbose_name_plural': 'Agent Audit Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
