# Generated by Django 6.0.3 on 2026-03-27 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_agent_queue'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='admin_pin_hash',
            field=models.CharField(blank=True, default='', help_text='SHA-256 hash of the admin PIN for banking data access', max_length=128),
        ),
    ]
