# Generated by Django 6.0.3 on 2026-03-27 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_change_auditlog_user_on_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='client_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='client_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='invoice',
            name='client_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='invoice',
            name='client_phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.client'),
        ),
    ]
