# Generated by Django 5.2.12 on 2026-05-13 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_invoice_manual_client'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='apikey',
            index=models.Index(fields=['is_active', 'created_at'], name='app_apikey_is_acti_41458d_idx'),
        ),
        migrations.AddIndex(
            model_name='apikey',
            index=models.Index(fields=['app_name', 'created_at'], name='app_apikey_app_nam_918760_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['start_time'], name='app_assignm_start_t_2eebff_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['status', 'start_time'], name='app_assignm_status_7138d5_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action', 'timestamp'], name='app_auditlo_action_2c455e_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['model_name', 'timestamp'], name='app_auditlo_model_n_a601c5_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['channel', 'status'], name='app_campaig_channel_54e0df_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['status', 'start_date'], name='app_campaig_status_965324_idx'),
        ),
        migrations.AddIndex(
            model_name='clientpayment',
            index=models.Index(fields=['status', 'payment_date'], name='app_clientp_status_05fcc7_idx'),
        ),
        migrations.AddIndex(
            model_name='clientpayment',
            index=models.Index(fields=['payment_method', 'payment_date'], name='app_clientp_payment_8adf2c_idx'),
        ),
        migrations.AddIndex(
            model_name='contactmessage',
            index=models.Index(fields=['processed', 'created_at'], name='app_contact_process_1fb496_idx'),
        ),
        migrations.AddIndex(
            model_name='contractinvitation',
            index=models.Index(fields=['status', 'created_at'], name='app_contrac_status_8ab42b_idx'),
        ),
        migrations.AddIndex(
            model_name='contractinvitation',
            index=models.Index(fields=['interpreter', 'status'], name='app_contrac_interpr_227935_idx'),
        ),
        migrations.AddIndex(
            model_name='contractreminder',
            index=models.Index(fields=['level', 'sent_at'], name='app_contrac_level_59c244_idx'),
        ),
        migrations.AddIndex(
            model_name='deduction',
            index=models.Index(fields=['date', 'deduction_type'], name='app_deducti_date_b2a261_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['status', 'created_at'], name='app_documen_status_c91a29_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['status', 'date_incurred'], name='app_expense_status_103bff_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['expense_type', 'date_incurred'], name='app_expense_expense_979fb1_idx'),
        ),
        migrations.AddIndex(
            model_name='financialtransaction',
            index=models.Index(fields=['type', 'date'], name='app_financi_type_b4ef9e_idx'),
        ),
        migrations.AddIndex(
            model_name='interpretercontractsignature',
            index=models.Index(fields=['status', 'signed_at'], name='app_interpr_status_319cfb_idx'),
        ),
        migrations.AddIndex(
            model_name='interpretercontractsignature',
            index=models.Index(fields=['is_active', 'created_at'], name='app_interpr_is_acti_c5bebf_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status', 'issued_date'], name='app_invoice_status_4e0daa_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['due_date'], name='app_invoice_due_dat_4e8383_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['created_at'], name='app_invoice_created_1d8b69_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['source', 'created_at'], name='app_lead_source_19ddc9_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['stage', 'created_at'], name='app_lead_stage_6d08b5_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['type', 'created_at'], name='app_notific_type_f4f82a_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['read', 'created_at'], name='app_notific_read_f16430_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'read'], name='app_notific_recipie_990bf6_idx'),
        ),
        migrations.AddIndex(
            model_name='onboardinginvitation',
            index=models.Index(fields=['current_phase', 'created_at'], name='app_onboard_current_ac6b83_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', 'payment_date'], name='app_payment_status_902271_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_type', 'payment_date'], name='app_payment_payment_0717db_idx'),
        ),
        migrations.AddIndex(
            model_name='payrolldocument',
            index=models.Index(fields=['document_date'], name='app_payroll_documen_48540f_idx'),
        ),
        migrations.AddIndex(
            model_name='payrolldocument',
            index=models.Index(fields=['created_at'], name='app_payroll_created_f0eb26_idx'),
        ),
        migrations.AddIndex(
            model_name='pgpkey',
            index=models.Index(fields=['is_active', 'expires_at'], name='app_pgpkey_is_acti_02bc9d_idx'),
        ),
        migrations.AddIndex(
            model_name='publicquoterequest',
            index=models.Index(fields=['processed', 'created_at'], name='app_publicq_process_06f159_idx'),
        ),
        migrations.AddIndex(
            model_name='publicquoterequest',
            index=models.Index(fields=['state', 'created_at'], name='app_publicq_state_bd701a_idx'),
        ),
        migrations.AddIndex(
            model_name='quoterequest',
            index=models.Index(fields=['status', 'created_at'], name='app_quotere_status_95a298_idx'),
        ),
        migrations.AddIndex(
            model_name='reimbursement',
            index=models.Index(fields=['date', 'reimbursement_type'], name='app_reimbur_date_a6a019_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['date'], name='app_service_date_45c52d_idx'),
        ),
    ]
