"""
Django settings for translation_platform project.

Generated by 'django-admin startproject' using Django 5.1.4.
"""
import base64
import tempfile

from django.core.exceptions import ImproperlyConfigured

from pathlib import Path
import os
from dotenv import load_dotenv
from datetime import timedelta
import dj_database_url

from django.utils.translation import gettext_lazy as _
from django.core.management.utils import get_random_secret_key

# Charger les variables d'environnement
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
SECRET_KEY = os.getenv('SECRET_KEY')
ENCRYPTION_KEY=os.getenv('ENCRYPTION_KEY')
DEBUG = os.getenv('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '').split(',') if os.getenv('ALLOWED_HOSTS') else []
SITE_URL = os.getenv('SITE_URL', 'https://jhbridgetranslation.com')

# Configuration pour l'authentification par clé API
API_KEY_HEADER = os.environ.get('API_KEY_HEADER', 'X-API-Key')
API_KEY_QUERY_PARAM = os.environ.get('API_KEY_QUERY_PARAM', 'api_key')
API_KEY_AUTH_HEADER_PREFIX = os.environ.get('API_KEY_AUTH_HEADER_PREFIX', 'Api-Key')

# URLs exemptées d'authentification par clé API
API_KEY_EXEMPT_URLS = os.environ.get('API_KEY_EXEMPT_URLS', '/admin/,/api/docs/,/api/auth/,^/api/public/')
if isinstance(API_KEY_EXEMPT_URLS, str):
    API_KEY_EXEMPT_URLS = [url.strip() for url in API_KEY_EXEMPT_URLS.split(',') if url.strip()]

# Mode strict
API_KEY_STRICT_MODE = os.environ.get('API_KEY_STRICT_MODE', 'False').lower() in ('true', '1', 't')


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',  # Format plus simple pour la production
            'level': 'WARNING' if not DEBUG else 'INFO',  # Niveau conditionnel
        },
    },
    'loggers': {
        # Configuration du logger racine
        '': {
            'handlers': ['console'],
            'level': 'WARNING' if not DEBUG else 'INFO',
        },
        # Configuration spécifique Django
        'django': {
            'handlers': ['console'],
            'level': 'ERROR' if not DEBUG else 'INFO',
            'propagate': False,
        },
        # Configuration spécifique pour les emails (source du problème)
        'django.core.mail': {
            'handlers': ['console'],
            'level': 'ERROR',  # Seulement les erreurs d'email
            'propagate': False,
        },
        # Configuration pour les requêtes (peut être verbeux)
        'django.request': {
            'handlers': ['console'],
            'level': 'ERROR',
            'propagate': False,
        },
        # Configuration pour les requêtes de base de données
        'django.db.backends': {
            'handlers': ['console'],
            'level': 'ERROR' if not DEBUG else 'INFO',
            'propagate': False,
        },
        # Logger pour votre application (ajustez le nom)
        'your_app_name': {  # Remplacez par le nom de votre app
            'handlers': ['console'],
            'level': 'INFO' if not DEBUG else 'DEBUG',
            'propagate': False,
        },
    },
}

# Configuration supplémentaire pour Railway
import os
if os.getenv('RAILWAY_ENVIRONMENT'):  # Détection de Railway
    # En production Railway, logs encore plus restrictifs
    LOGGING['handlers']['console']['level'] = 'ERROR'
    LOGGING['loggers']['']['level'] = 'ERROR'
    LOGGING['loggers']['django']['level'] = 'ERROR'
    LOGGING['loggers']['django.core.mail']['level'] = 'CRITICAL'  # Presque pas de logs email

# Application definition
INSTALLED_APPS = [
    # Local apps (mettre en premier)
    "app",
    'storages',
    # Django built-in apps
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'widget_tweaks',
    # Third party apps
    'phonenumber_field',
    'django_countries',
    'django_apscheduler',
    'corsheaders',
    'rest_framework',
    'rest_framework_simplejwt',
    'crispy_tailwind',
    'django_celery_beat',
    'social_django',
    'crispy_forms',
    'crispy_bootstrap5',
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",  # Internationalisation middleware
    "whitenoise.middleware.WhiteNoiseMiddleware", 
    "app.api_auth.middleware.APIKeyMiddleware",
    'corsheaders.middleware.CorsMiddleware',
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    'social_django.middleware.SocialAuthExceptionMiddleware',
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            BASE_DIR / 'templates',
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                'social_django.context_processors.backends',
                'social_django.context_processors.login_redirect',
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"

# Database
DATABASES = {
    'default': dj_database_url.config(
        default=os.getenv('MYSQL_URL'),
        conn_max_age=600
    )
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization settings
LANGUAGE_CODE = "en-us"
TIME_ZONE = "America/New_York"  # Fuseau horaire pour le Massachusetts

# Available languages
LANGUAGES = [
    ('en', _('English')),
]

# Directory where translation files are stored
LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

USE_I18N = True  # Enable internationalization
USE_L10N = True  # Enable localization
USE_TZ = True  # Enable timezone support

# Date and Time Formatting
DATE_FORMAT = 'N j, Y'  # Example: Jan. 1, 2024
DATETIME_FORMAT = 'N j, Y, P'  # Example: Jan. 1, 2024, 4 p.m.
SHORT_DATE_FORMAT = 'm/d/Y'  # US format: MM/DD/YYYY
SHORT_DATETIME_FORMAT = 'm/d/Y P'

# Number Formatting
USE_THOUSAND_SEPARATOR = True
THOUSAND_SEPARATOR = ','
NUMBER_GROUPING = 3
DECIMAL_SEPARATOR = '.'

# Date Input Formats
DATE_INPUT_FORMATS = [
    '%m/%d/%Y',  # US format MM/DD/YYYY
    '%Y-%m-%d',  # ISO format
]

# Time Input Formats
TIME_INPUT_FORMATS = [
    '%I:%M %p',  # 12-hour format with AM/PM
    '%H:%M',     # 24-hour format
]

# Static files (CSS, JavaScript, Images)
STATIC_URL = "static/"
STATICFILES_DIRS = [
    BASE_DIR / "static",
]
STATIC_ROOT = BASE_DIR / "staticfiles"

# Default primary key field type
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# REST Framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        #"app.api_auth.authentication.APIKeyAuthentication",
    ),
    'DATETIME_FORMAT': '%Y-%m-%dT%H:%M:%S%z',
    'DATE_FORMAT': '%Y-%m-%d',
    'TIME_FORMAT': '%H:%M:%S',
    'DATETIME_INPUT_FORMATS': [
        '%Y-%m-%dT%H:%M:%S%z',
        '%Y-%m-%d %H:%M:%S',
        '%Y-%m-%d %H:%M',
    ],
}

# JWT Settings
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(seconds=int(os.getenv('JWT_ACCESS_TOKEN_LIFETIME', 3600))),
    'REFRESH_TOKEN_LIFETIME': timedelta(seconds=int(os.getenv('JWT_REFRESH_TOKEN_LIFETIME', 86400))),
    'SIGNING_KEY': os.getenv('JWT_SECRET_KEY', SECRET_KEY),
}

# CORS Settings
CORS_ALLOWED_ORIGINS = os.getenv('CORS_ALLOWED_ORIGINS', '').split(',') if os.getenv('CORS_ALLOWED_ORIGINS') else []
CORS_ALLOW_CREDENTIALS = os.getenv('CORS_ALLOW_CREDENTIALS', 'True') == 'True'
CSRF_TRUSTED_ORIGINS = os.getenv('CSRF_TRUSTED_ORIGINS', '').split(',') if os.getenv('CSRF_TRUSTED_ORIGINS') else []

# Email Configuration
# Pour tester sans SMTP
EMAIL_BACKEND = 'app.backends.resend_backend.ResendEmailBackend'
RESEND_API_KEY = os.getenv('RESEND_API_KEY')
DEFAULT_FROM_EMAIL = "dispatch@jhbridgetranslation.com"
#QUOTE_NOTIFICATION_EMAIL = os.getenv('DEFAULT_FROM_EMAIL')
#EMAIL_HOST = os.getenv('EMAIL_HOST')
#EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587))
#EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
#EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
#EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True') == 'True'
#EMAIL_USE_SSL = os.getenv('EMAIL_USE_SSL', 'False') == 'True'
#DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL')
#CONTACT_NOTIFICATION_EMAIL = os.getenv('DEFAULT_FROM_EMAIL')
EMAIL_TIMEOUT = 10  # Ajoutez un timeout


# Celery Configuration
CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL')
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE

# Social Auth Configuration
AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
)

SOCIAL_AUTH_GOOGLE_OAUTH2_KEY =('SOCIAL_AUTH_GOOGLE_CLIENT_ID')
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = os.getenv('SOCIAL_AUTH_GOOGLE_CLIENT_SECRET')

# Stripe Configuration
STRIPE_SECRET_KEY = os.getenv('STRIPE_SECRET_KEY')
STRIPE_PUBLISHABLE_KEY = os.getenv('STRIPE_PUBLISHABLE_KEY')

# Login/Logout URLs
LOGIN_URL = 'dbdint:login'
LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_URL = 'logout'
LOGOUT_REDIRECT_URL = 'home'

# Phone number settings
PHONENUMBER_DEFAULT_REGION = 'US'
PHONENUMBER_DB_FORMAT = 'INTERNATIONAL'

# Crispy Forms
CRISPY_ALLOWED_TEMPLATE_PACKS = ('bootstrap5',)
CRISPY_TEMPLATE_PACK = 'bootstrap5'

# Scheduler Configuration
SCHEDULER_CONFIG = {
    "apscheduler.jobstores.default": {
        "class": "django_apscheduler.jobstores:DjangoJobStore",
    },
    "apscheduler.executors.default": {
        "class": "apscheduler.executors.pool:ThreadPoolExecutor",
        "max_workers": 20,
    },
    "apscheduler.job_defaults": {
        "coalesce": False,
        "max_instances": 1,
    },
    "apscheduler.timezone": TIME_ZONE,
}

# Scheduler Config Variables
SCHEDULER_AUTOSTART = True
SCHEDULER_REMOVE_EXISTING_JOBS = True
AUTH_USER_MODEL = 'app.User'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Storage Configuration


# Limites de taille pour les uploads
FILE_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10MB pour la mémoire par défaut
DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10MB pour les requêtes POST
VIDEO_MAX_SIZE = 50 * 1024 * 1024  # 50MB pour les vidéos
IMAGE_MAX_SIZE = 5 * 1024 * 1024   # 5MB pour les images



# Configuration AWS S3 pour django-storages
AWS_ACCESS_KEY_ID = os.getenv('AWS_KEY_ID') or os.getenv('AWS_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = os.getenv('AWS_KEY_SECRET') or os.getenv('AWS_SECRET_ACCESS_KEY')
AWS_S3_REGION_NAME = os.getenv('AWS_S3_REGION_NAME', 'us-east-1')
AWS_S3_SIGNATURE_VERSION = 's3v4'
AWS_QUERYSTRING_AUTH = True  # Par défaut, liens signés (sécurité)

# Configuration moderne des storages
STORAGES = {
    "default": {
        "BACKEND": "custom_storages.MediaStorage", 
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        # Si vous vouliez servir les static files depuis S3 'jhbridge-assets', changez ici:
        # "BACKEND": "custom_storages.AssetStorage",
    }
}

# Configuration Legacy (pour compatibilité)
DEFAULT_FILE_STORAGE = "custom_storages.MediaStorage"

MASTER_KEY = os.environ.get('MASTER_KEY', '')
PDF_GENERATOR_API_KEY = os.getenv('PDF_GENERATOR_API_KEY')
API_URL_PDF_GENERATOR=os.getenv('API_URL_PDF_GENERATOR')

