"""
Type-safe Enum wrappers around the shared constants.
Use these when you need exhaustive matching or IDE autocomplete.
"""

from enum import Enum

from shared.constants import (
    ROLE_CLIENT, ROLE_INTERPRETER, ROLE_ADMIN,
    QUOTE_REQUEST_PENDING, QUOTE_REQUEST_PROCESSING, QUOTE_REQUEST_QUOTED,
    QUOTE_REQUEST_ACCEPTED, QUOTE_REQUEST_REJECTED, QUOTE_REQUEST_EXPIRED,
    QUOTE_DRAFT, QUOTE_SENT, QUOTE_ACCEPTED, QUOTE_REJECTED,
    QUOTE_EXPIRED, QUOTE_CANCELLED,
    ASSIGNMENT_PENDING, ASSIGNMENT_CONFIRMED, ASSIGNMENT_IN_PROGRESS,
    ASSIGNMENT_COMPLETED, ASSIGNMENT_CANCELLED, ASSIGNMENT_NO_SHOW,
)


class UserRole(str, Enum):
    CLIENT = ROLE_CLIENT
    INTERPRETER = ROLE_INTERPRETER
    ADMIN = ROLE_ADMIN


class QuoteRequestStatus(str, Enum):
    PENDING = QUOTE_REQUEST_PENDING
    PROCESSING = QUOTE_REQUEST_PROCESSING
    QUOTED = QUOTE_REQUEST_QUOTED
    ACCEPTED = QUOTE_REQUEST_ACCEPTED
    REJECTED = QUOTE_REQUEST_REJECTED
    EXPIRED = QUOTE_REQUEST_EXPIRED


class QuoteStatus(str, Enum):
    DRAFT = QUOTE_DRAFT
    SENT = QUOTE_SENT
    ACCEPTED = QUOTE_ACCEPTED
    REJECTED = QUOTE_REJECTED
    EXPIRED = QUOTE_EXPIRED
    CANCELLED = QUOTE_CANCELLED


class AssignmentStatus(str, Enum):
    PENDING = ASSIGNMENT_PENDING
    CONFIRMED = ASSIGNMENT_CONFIRMED
    IN_PROGRESS = ASSIGNMENT_IN_PROGRESS
    COMPLETED = ASSIGNMENT_COMPLETED
    CANCELLED = ASSIGNMENT_CANCELLED
    NO_SHOW = ASSIGNMENT_NO_SHOW
